/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        'filament.exports.download': [
            {
                'name': 'export';
                'binding': 'id';
            },
        ];
        'filament.imports.failed-rows.download': [
            {
                'name': 'import';
                'binding': 'id';
            },
        ];
        'filament.admin.auth.logout': [];
        'filament.admin.pages.dashboard': [];
        'login': [];
        'logout': [];
        'password.request': [];
        'password.reset': [
            {
                'name': 'token';
            },
        ];
        'password.email': [];
        'password.update': [];
        'register': [];
        'verification.notice': [];
        'verification.verify': [
            {
                'name': 'id';
            },
            {
                'name': 'hash';
            },
        ];
        'verification.send': [];
        'user-profile-information.update': [];
        'user-password.update': [];
        'password.confirmation': [];
        'password.confirm': [];
        'two-factor.login': [];
        'two-factor.enable': [];
        'two-factor.confirm': [];
        'two-factor.disable': [];
        'two-factor.qr-code': [];
        'two-factor.secret-key': [];
        'two-factor.recovery-codes': [];
        'profile.show': [];
        'other-browser-sessions.destroy': [];
        'current-user-photo.destroy': [];
        'current-user.destroy': [];
        'teams.create': [];
        'teams.store': [];
        'teams.show': [
            {
                'name': 'team';
            },
        ];
        'teams.update': [
            {
                'name': 'team';
            },
        ];
        'teams.destroy': [
            {
                'name': 'team';
            },
        ];
        'current-team.update': [];
        'team-members.store': [
            {
                'name': 'team';
            },
        ];
        'team-members.update': [
            {
                'name': 'team';
            },
            {
                'name': 'user';
            },
        ];
        'team-members.destroy': [
            {
                'name': 'team';
            },
            {
                'name': 'user';
            },
        ];
        'team-invitations.accept': [
            {
                'name': 'invitation';
            },
        ];
        'team-invitations.destroy': [
            {
                'name': 'invitation';
            },
        ];
        'passport.token': [];
        'passport.authorizations.authorize': [];
        'passport.token.refresh': [];
        'passport.authorizations.approve': [];
        'passport.authorizations.deny': [];
        'passport.tokens.index': [];
        'passport.tokens.destroy': [
            {
                'name': 'token_id';
            },
        ];
        'passport.clients.index': [];
        'passport.clients.store': [];
        'passport.clients.update': [
            {
                'name': 'client_id';
            },
        ];
        'passport.clients.destroy': [
            {
                'name': 'client_id';
            },
        ];
        'passport.scopes.index': [];
        'passport.personal.tokens.index': [];
        'passport.personal.tokens.store': [];
        'passport.personal.tokens.destroy': [
            {
                'name': 'token_id';
            },
        ];
        'livewire.update': [];
        'livewire.upload-file': [];
        'livewire.preview-file': [
            {
                'name': 'filename';
            },
        ];
        'ignition.healthCheck': [];
        'ignition.executeSolution': [];
        'ignition.updateConfig': [];
        'dashboard': [];
    }
}
export {};
