/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        'scramble.docs.index': [];
        'scramble.docs.api': [];
        'filament.exports.download': [
            {
                'name': 'export';
                'required': true;
                'binding': 'id';
            },
        ];
        'filament.imports.failed-rows.download': [
            {
                'name': 'import';
                'required': true;
                'binding': 'id';
            },
        ];
        'filament.admin.auth.logout': [];
        'filament.admin.pages.dashboard': [];
        'filament.admin.resources.clients.index': [];
        'filament.admin.resources.clients.create': [];
        'filament.admin.resources.clients.edit': [
            {
                'name': 'record';
                'required': true;
            },
        ];
        'filament.admin.resources.organizations.index': [];
        'filament.admin.resources.organizations.create': [];
        'filament.admin.resources.organizations.edit': [
            {
                'name': 'record';
                'required': true;
            },
        ];
        'filament.admin.resources.projects.index': [];
        'filament.admin.resources.projects.create': [];
        'filament.admin.resources.projects.edit': [
            {
                'name': 'record';
                'required': true;
            },
        ];
        'filament.admin.resources.tags.index': [];
        'filament.admin.resources.tags.create': [];
        'filament.admin.resources.tags.edit': [
            {
                'name': 'record';
                'required': true;
            },
        ];
        'filament.admin.resources.tasks.index': [];
        'filament.admin.resources.tasks.create': [];
        'filament.admin.resources.tasks.edit': [
            {
                'name': 'record';
                'required': true;
            },
        ];
        'filament.admin.resources.time-entries.index': [];
        'filament.admin.resources.time-entries.create': [];
        'filament.admin.resources.time-entries.edit': [
            {
                'name': 'record';
                'required': true;
            },
        ];
        'filament.admin.resources.users.index': [];
        'filament.admin.resources.users.create': [];
        'filament.admin.resources.users.edit': [
            {
                'name': 'record';
                'required': true;
            },
        ];
        'login': [];
        'logout': [];
        'password.request': [];
        'password.reset': [
            {
                'name': 'token';
                'required': true;
            },
        ];
        'password.email': [];
        'password.update': [];
        'register': [];
        'verification.notice': [];
        'verification.verify': [
            {
                'name': 'id';
                'required': true;
            },
            {
                'name': 'hash';
                'required': true;
            },
        ];
        'verification.send': [];
        'user-profile-information.update': [];
        'user-password.update': [];
        'password.confirmation': [];
        'password.confirm': [];
        'two-factor.login': [];
        'two-factor.enable': [];
        'two-factor.confirm': [];
        'two-factor.disable': [];
        'two-factor.qr-code': [];
        'two-factor.secret-key': [];
        'two-factor.recovery-codes': [];
        'profile.show': [];
        'other-browser-sessions.destroy': [];
        'current-user-photo.destroy': [];
        'current-user.destroy': [];
        'teams.create': [];
        'teams.store': [];
        'teams.show': [
            {
                'name': 'team';
                'required': true;
            },
        ];
        'teams.update': [
            {
                'name': 'team';
                'required': true;
            },
        ];
        'teams.destroy': [
            {
                'name': 'team';
                'required': true;
            },
        ];
        'current-team.update': [];
        'team-members.store': [
            {
                'name': 'team';
                'required': true;
            },
        ];
        'team-members.update': [
            {
                'name': 'team';
                'required': true;
            },
            {
                'name': 'user';
                'required': true;
            },
        ];
        'team-members.destroy': [
            {
                'name': 'team';
                'required': true;
            },
            {
                'name': 'user';
                'required': true;
            },
        ];
        'team-invitations.accept': [
            {
                'name': 'invitation';
                'required': true;
            },
        ];
        'team-invitations.destroy': [
            {
                'name': 'invitation';
                'required': true;
            },
        ];
        'passport.token': [];
        'passport.authorizations.authorize': [];
        'passport.token.refresh': [];
        'passport.authorizations.approve': [];
        'passport.authorizations.deny': [];
        'passport.tokens.index': [];
        'passport.tokens.destroy': [
            {
                'name': 'token_id';
                'required': true;
            },
        ];
        'passport.clients.index': [];
        'passport.clients.store': [];
        'passport.clients.update': [
            {
                'name': 'client_id';
                'required': true;
            },
        ];
        'passport.clients.destroy': [
            {
                'name': 'client_id';
                'required': true;
            },
        ];
        'passport.scopes.index': [];
        'passport.personal.tokens.index': [];
        'passport.personal.tokens.store': [];
        'passport.personal.tokens.destroy': [
            {
                'name': 'token_id';
                'required': true;
            },
        ];
        'livewire.update': [];
        'livewire.upload-file': [];
        'livewire.preview-file': [
            {
                'name': 'filename';
                'required': true;
            },
        ];
        'ignition.healthCheck': [];
        'ignition.executeSolution': [];
        'ignition.updateConfig': [];
        'api.v1.organizations.show': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.organizations.update': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.users.index': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.users.invite-placeholder': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
            {
                'name': 'user';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.projects.index': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.projects.show': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
            {
                'name': 'project';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.projects.store': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.projects.update': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
            {
                'name': 'project';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.projects.destroy': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
            {
                'name': 'project';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.time-entries.index': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.time-entries.store': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.time-entries.update': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
            {
                'name': 'timeEntry';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.time-entries.destroy': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
            {
                'name': 'timeEntry';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.tags.index': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.tags.store': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.tags.update': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
            {
                'name': 'tag';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.tags.destroy': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
            {
                'name': 'tag';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.clients.index': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.clients.store': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.clients.update': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
            {
                'name': 'client';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.clients.destroy': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
            {
                'name': 'client';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.tasks.index': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.tasks.store': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.tasks.update': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
            {
                'name': 'task';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.tasks.destroy': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
            {
                'name': 'task';
                'required': true;
                'binding': 'id';
            },
        ];
        'api.v1.import.import': [
            {
                'name': 'organization';
                'required': true;
                'binding': 'id';
            },
        ];
        'dashboard': [];
        'telescope': [
            {
                'name': 'view';
                'required': false;
            },
        ];
        'api.': [
            {
                'name': 'fallbackPlaceholder';
                'required': true;
            },
        ];
    }
}
export {};
