name: NPM Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.1'
          extensions: intl, zip
      - run: composer install
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: composer generate-typescript
      - run: npm run lint:fix
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v17
        id: verify-changed-files
        with:
          fail-if-changed: true
          fail-message: 'The models.ts file is not up to date. Please run `composer generate-typescript` locally and commit the changes.'
          files: |
            resources/js/types/models.ts
