name: PHP Linting
on: push
permissions:
  contents: read
jobs:
  pint:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 10

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v7

      - name: "Check code style"
        uses: aglipanci/laravel-pint-action@2.6
        with:
          configPath: "pint.json"
